version: '3.8'
services:
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
      - client_data:/app/public
    stdin_open: true
    tty: true

  api:
    build:
     context: ./server
     dockerfile: Dockerfile
    container_name: api_backend
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - api_node_modules:/app/node_modules
      - api_data:/app/static
    environment:
      - PG_DB=ONline_store
      - PG_USER=postgres
      - PG_PASSWORD=1111
      - PG_HOST=db
    depends_on:
      - db

  db:
    container_name: api_db
    image: postgres:12
    environment:
      - POSTGRES_DB=ONline_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8081:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes:
  api_node_modules:
  client_node_modules:
  client_data:
  api_data:
  db_data: { }