version: '3.8'
services:
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  api:
    build:
     context: ./server
     dockerfile: Dockerfile
    container_name: api_backend
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - api_node_modules:/app/node_modules
      - api_data:/app/static
    environment:
      - PG_DB=ONline_store
      - PG_USER=postgres
      - PG_PASSWORD=1111
      - PG_HOST=db
    depends_on:
      - db

  db:
    container_name: api_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ONline_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    volumes:
      - ./pgadmin:/var/lib/pgadmin

volumes:
  api_node_modules:
  api_data:
  db_data: { }